# Generated by Django 4.2 on 2024-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='file/%Y/%m/%d', verbose_name='File'),
        ),
    ]
